### ISSUE TITLE
Enrichment

### ISSUE THREAD

**Issue by antonioam97** [hiyin/interferome-2016#2]
I have a problem with the enrichment. I use de command line and obtain this message when i execute it:

Exception in thread "main" java.lang.NullPointerException
	at analysis.promotersites.PromoterList.removeOverlappingPromoters(PromoterList.java:197)
	at workflow.Workflow.run(Workflow.java:224)
	at workflow.Workflow.main(Workflow.java:110)

**Comment by hiyin** [comment]
Hi, this project is an enterprise-level project. What are you using it for? You need the Enrichment software for the enrichment to function normally which you probably won't have access to as it is hosted in internal server.
